# Linear Algebra - Chapter 4 (Data Science From Scratch)

In [1]:
import numpy as np

## Vector

Vectors are line segments used to represent a vector space, which is an oriented line segment with magnitude, direction and direction. A vector is represented with three coordinates, x, y and z. <br>
We can also think of a vector as a list, as attributes, a column, a 3d space vector, etc.

In [2]:
vector_3d = np.array([1,2,3]) #space vector
grades = np.array([4,5,5,6,7,8,10])
person_attr = np.array([1.75, 70, 24]) #h, w, age

### Operations -> Add, Sub and scalar mult

All these operations are done component-wise and produce a new vector, e.g.: V1x + V2x; V1y + V2y ...

In [3]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [4]:
np.array([1,2,3]) - np.array([4,5,6])

array([-3, -3, -3])

In [5]:
np.array([1,2,3]) * 4

array([ 4,  8, 12])

### TODO -> arrays mean

In [6]:
(np.array([1,2,3]) + np.array([4,5,6]))/2

array([2.5, 3.5, 4.5])

### TODO -> dot product

In [7]:
np.dot(np.array([1,2,3]), np.array([4,5,6]))

32

### TODO -> array projection

In [8]:
#array projection - each axis
print(np.dot(np.array([1,2,3]), np.array([1,0,0])))
print(np.dot(np.array([1,2,3]), np.array([0,1,0])))
print(np.dot(np.array([1,2,3]), np.array([0,0,1])))

1
2
3


### TODO -> sum of squares

In [9]:
#Sum of squares
vector = np.array([1,2,3])
np.dot(vector, vector)

14